/** @type {import('tailwindcss').Config} */
module.exports = {
   presets: [require("nativewind/preset")],
   content:[
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./screens/**/*.{js,ts,jsx,tsx}",
   ],
   theme:{
    extend:{
        fontFamily:{
            poppins:["Poppins-Regular"],
            "poppins-medium":["Poppins-Medium"],
            "poppins-semibold":["Poppins-SemiBold"],
            "poppins-bold":["Poppins-Bold"],
            railway:["Railway"],
            "railway-bold":["Railway-Bold"],
            inter:["Inter-Regular"],
            "inter-semibold":["Inter-SemiBold"],
            "inter-bold":["Inter-Bold"],
        },
        colors:{
            primary:"#007AFF",
            secondary:"#5AC8FA",
            accent:"#FF2D55",
            success:"#34C759",
            warning:"#FF9500",
            danger:"#FF3B30",
            info:"#00C7FD",
            light:"#F2F2F7",
            dark:"#000000",
            muted:"#8E8E93",
            border:"#E5E5EA",
            background:"#FFFFFF",
        },
        spacing:{
            xs:"4px",
            sm:"8px",
            md:"12px",
            lg:"16px",
            xl:"20px",
            "2xl":"24px",
            "3xl":"32px",
            "4xl":"40px",
        },
        borderRadius:{
            sm:"4px",
            md:"8px",
            lg:"12px",
            xl:"16px",
            "2xl":"20px",
            full:"9999px",
        },
        fontSize:{
            xs:["12px","16px"],
            sm:["14px","20px"],
            base:["16px","24px"],
            lg:["18px","28px"],
            xl:["20px","28px"],
            "2xl":["24px","32px"],
            "3xl":["32px","40px"],
        },
        boxShadow:{
            sm:"0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            md:"0 4px 6px -1px rgba(0, 0, 0, 0.1)",
            lg:"0 10px 15px -3px rgba(0, 0, 0, 0.1)",
            xl:"0 20px 25px -5px rgba(0, 0, 0, 0.1)",
            "2xl":"0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        },
        opacity:{
            0:"0",
            5:"0.05",
            10:"0.1",
            20:"0.2",
            30:"0.3",
            40:"0.4",
            50:"0.5",
            60:"0.6",
            70:"0.7",
            80:"0.8",
            90:"0.9",
            100:"1",
        },
    }
   },
   plugins:[],
}